### ISSUE TITLE
--debug option

### ISSUE THREAD

**Issue by s-rodriguez** [pocesar/grunt-mocha-istanbul#69]
How can I set up my options so the `--debug-brk` flag is taken? It seems as if it's skipping it, and running the tests without breaking at start. (Same happens with the `--debug` flag)

This is what I have:

```
  options: {
    coverageFolder:  '.coverage',
    mochaOptions:    ['--bail', '--debug-brk', '--reporter', 'dot', '--timeout', '6000'],
    istanbulOptions: ['--preserve-comments'],
    reportFortmats:  ['lcov']
  }
```

**Comment by pocesar** [comment]
the `debug-brk` and `debug` flags, AFAIK, is a interactive state that is not possible when using sub spawned processes by istanbul, because there will be 2 running processes, mocha with the debug-brk spawned by istanbul node process that has no debug-brk, and this helper library wouldn't be able to handle this as well.

**Comment by s-rodriguez** [comment]
Oh ok, thanks for the clarification!
